### PR TITLE
Make the tests pass again

### PR DESCRIPTION
**Pull request by phuel**
Hi,

To make the tests pass again I updated the reference Python file fizz.py and I updated the handling of boolean values in the transpiler to be compatible with the previous change.

Cheers
     Peter

### CODE REVIEW

**Comment by yyyyyyyan** [comment]
I'm sorry, could you explain your changes a bit more? I've stopped keeping up with Rockstar docs for a while, but the transpiler for sure won't work if you simply remove all elements of the poetic literals list.

**Comment by phuel** [comment]
Hi,

thank you for your fast response.
I think the before the transpiler calls 'find_poetic_number_literal' in line 148 it replaces all occurrences of 'simple_subs' in the lines starting at 142.
So 'find_poetic_number_literal' actually never sees the strings like 'true', 'false', 'nothing' and so on, but only their replacements 'True' and 'False'.
The change makes the tests pass and before the change the line 'My world is empty' in fizz.rock was translated to 'my_world = 5'.
As I write this, I think that perhaps the fix is not complete yet. There are other strings as replacements in 'simple_subs' than only 'True' and 'False'. I need to think if they can show up in 'find_poetic_number_literal'.

Cheers
       Peter

**Comment by phuel** [comment]
The other strings ('return', 'continue' and the like) can't make it into 'find_poetic_number_literal' because they all start a line.

**Comment by yyyyyyyan** [comment]
Sorry for the slow response! I'll check this out next week, been really busy these days. Thanks very much!

**Comment by yyyyyyyan** [comment]
Thanks very much, @phuel! I'm accepting it now, just tested it and it seems great. I'll fix some old stuff and release a new version.

**Pull request merged**
